# Generated by Django 5.1 on 2024-08-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_gastronomic_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomic',
            name='image',
            field=models.ImageField(upload_to='gastronomic/images'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='image',
            field=models.ImageField(upload_to='hosting/images'),
        ),
    ]
