# Generated by Django 5.1 on 2024-08-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_alter_gastronomic_image_alter_hosting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomic',
            name='image',
            field=models.ImageField(upload_to='tourist/images'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='image',
            field=models.ImageField(upload_to='tourist/images'),
        ),
    ]
